#!/bin/bash

if [ "$(whoami)" != "root" ]; then
  echo "This script must be run as root (e.g. sudo)"
  exit 1
else
  (odr-dabmux demo.mux |
  odr-dabmod -f /dev/stdout -g0 -m 1 -r 3200000 |
  python2 demo.py)
fi

